name: pub_packages
description: Pub Packages
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.18.0-78.0.dev <3.0.0'
  flutter: '>=2.13.0-0.0.pre.868'

dependencies:
  flutter:
    sdk: flutter
  equatable: any
  json_annotation: any
  l: ^3.2.0
  go_router: ^3.1.0
  meta: ^1.7.0
  freezed_annotation: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  build_web_compilers: ^3.2.1
  build_runner: ^2.1.10
  grinder: ^0.9.1
  path: ^1.8.1
  go_router_builder: ^1.0.1
  freezed: ^2.0.2
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.1+1
  pubspec_generator: ^3.0.1
  flutter_gen_runner: ^4.0.1
  #pub_api_client: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/packages.json

# Flutter assets codegen
flutter_gen:
  output: lib/src/common/constant/
  line_length: 120

# Generate app icon
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/icon/1x/icon.png"
  image_path_android: "assets/icon/1x/icon.png"
  image_path_ios: "assets/icon/1x/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/icons/background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/icons/foreground.png" # only available for Android 8.0 devices and above

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#cfd8dc"
  #background_image: "assets/background.png"

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/splash/image.png