name: pub_packages
description: Pub Packages
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.18.0-78.0.dev <3.0.0'
  flutter: '>=2.13.0-0.0.pre.868'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  equatable: any
  json_annotation: any
  l: ^3.2.0
  go_router: ^3.1.0
  meta: ^1.7.0
  freezed_annotation: ^2.0.1
  shared_preferences: ^2.0.13
  url_launcher: ^6.1.0
  firebase: ^9.0.2
  firebase_core: ^1.16.0
  firebase_analytics: ^9.1.7
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  flutterfire_ui: ^0.4.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  build_web_compilers: ^3.2.1
  build_runner: ^2.1.10
  grinder: ^0.9.1
  path: ^1.8.1
  go_router_builder: ^1.0.1
  freezed: ^2.0.2
  icons_launcher: ^1.1.3
  flutter_native_splash: ^2.0.1+1
  pubspec_generator: ^3.0.1
  flutter_gen_runner: ^4.0.1
  #pub_api_client: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/packages.json

# Flutter assets codegen
flutter_gen:
  output: lib/src/common/constant/
  line_length: 120

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#cfd8dc"
  #background_image: "assets/background.png"

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/splash/image.png